# Generated by Django 3.0.5 on 2020-04-29 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fetcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
